### ISSUE TITLE
Datapoint collection

### ISSUE THREAD

**Issue by soulfire89** [sebilm/ioBroker.myuplink#28]
Hey,
do you allready have a collection of all writeable datapoints from the main menu?
I found a way to get the ID's when using DevTools. The Network section shows each datapoint action inside the Myuplink GUI.

If there is no collection, I would offer to collect the ones from my Nibe VVM225/F2120-8 and share it here.

I can imagine that it would be great for a lot of users, having an adapter-menu to create a set of datapoint's in different languages. I've checked the functionality with "set data" datapoint from your adapter with these ID's and it worked:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=de style='font-family:Calibri;font-size:11.0pt'>

<div style='direction:ltr'>

  | Name | Einheit | Menü
-- | -- | -- | --
47027 | Außentemperaturpunkt | °C | 1.9.8
47028 | Kurvenänderung | °C | 1.9.8

I think there is an hidden API part called internalapi.myuplink.com which is used for non offical API datapoints: https://internalapi.myuplink.com/v3/devices/***

</div>

</body>

</html>

BR, Armin

**Comment by sebilm** [comment]
I'll have a look at it, but it may take a few weeks - I don't have that much time at the moment.

**Comment by soulfire89** [comment]
This is what I've collected the last days. Everything with german description. Tried to find the values for the different ID's. But it was difficult for button or checkbox ID's like 47260. There is only one ID with 5 different options. I couldn't find out which values were send when pressing them.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/u24f69/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/u24f69/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


ID | Name de-D | Name en-En | value | Einheit | Menü | Kategorie
-- | -- | -- | -- | -- | -- | --
47011 | Temperaturoffset |   | 0(aus);1(an) | on/off | 1.1.1 |  
47260 | normal |   | 0 |   | 1.2 | Ventilation
47260 | Ventilation   Geschw. 1 |   | 1 |   | 1.2 | Ventilation
47260 | Ventilation   Geschw. 2 |   | 2 |   | 1.2 | Ventilation
47260 | Ventilation   Geschw. 3 |   | 3 |   | 1.2 | Ventilation
47260 | Ventilation   Geschw. 4 |   | 4 |   | 1.2 | Ventilation
48132 | vorüb.   Luxus aus |   |   |   | 2.1 | vorüb. Luxus
48132 | vorüb.   Luxus 3 hrs |   |   |   | 2.1 | vorüb. Luxus
48132 | vorüb.   Luxus 6 hrs |   |   |   | 2.1 | vorüb. Luxus
48132 | vorüb.   Luxus 12 hrs |   |   |   | 2.1 | vorüb. Luxus
48132 | vorüb.   Luxus einm. Erhöhung |   |   |   | 2.1 | vorüb. Luxus
47041 | Sparm. |   |   |   | 2.2 | Komfortmodus
47041 | normal |   |   |   | 2.2 | Komfortmodus
47041 | Luxus |   |   |   | 2.2 | Komfortmodus
47274 | Ventilatorrückstellzeit   Geschw. 1 |   |   | hrs | 1.9.6 | Ventilatorrückstellzeit
47273 | Ventilatorrückstellzeit   Geschw. 2 |   |   | hrs | 1.9.6 | Ventilatorrückstellzeit
47272 | Ventilatorrückstellzeit   Geschw. 3 |   |   | hrs | 1.9.6 | Ventilatorrückstellzeit
47271 | Ventilatorrückstellzeit   Geschw. 4 |   |   | hrs | 1.9.6 | Ventilatorrückstellzeit
47027 | Außentemperaturpunkt |   |   | °C | 1.9.8 | Punktverschiebung
47028 | Kurvenänderung |   |   | °C | 1.9.8 | Punktverschiebung
47537 | Nachtabsenkung |   | 0(aus);1(an) | on/off | 1.9.9 | Nachtabsenkung
47538 | Starttemp.   Abluft: |   |   | °C | 1.9.9 | Nachtabsenkung
47539 | min.   Diff. Außen- und Abluft: |   |   | °C | 1.9.9 | Nachtabsenkung
40940 | Gradminuten   aktueller Wert |   | +--10 | DM | 4.9.3 | Gradminuteneinstellung
47206 | Gradminuten   Start Verdichter |   | +--10 | DM | 4.9.3 | Gradminuteneinstellung
48072 | Gradminuten   Startdifferenz Zusatzheizung |   | +--10 | DM | 4.9.3 | Gradminuteneinstellung
47209 | Gradminuten   Diff. Zw. ZH-Stufen |   | +--10 | DM | 4.9.3 | Gradminuteneinstellung



</body>

</html>

**Comment by MichaelSchaaf999** [comment]
Hi Armin,
what I can find for our SMO S40 F2120-16 are datapoints as follows, examples:
<img width="1062" alt="grafik" src="https://github.com/sebilm/ioBroker.myuplink/assets/53481090/85b3aa0b-11a4-48f3-a86a-b96743ff2b14">

In other words: I cannot see IDs following your example, means: NO 4xxxx IDs.
Is there any way to find the "translation" of our IDs, e.g. 11 = Brauch­wasser, oben (BT7) or 12 = Brauch­wasser­berei­tung (BT6) or 10733 = Lade­pumpen­dreh­zahl (EB101-GP12)?

BR, Micha

**Comment by soulfire89** [comment]
@MichaelSchaaf999 You can find these information when using DevTools at myuplink.com. The Network section shows each datapoint action inside the Myuplink GUI.
They were not delivered from iobroker adapter right now. But you can set most of them via "set data" datapoint.

**Comment by MichaelSchaaf999** [comment]
Dear Armin,
thanks a lot for your explanation. But, much better: I saw that you set the device "NAME" of each imported device as shown somewhere...  in the API I assume. I can see it in the tab-objects if the configuration of this tab-objects is set to show the names.
Means:
10733 -> Name= "Vorübergehend mehr BW"
That's awsome!

Question: Do you have any advice how to show that "name" in a GUI, in VIS, means: in a (text-)widget?
I have no idea how to access this datapoint's field "name" and show it in a view with the datapoint's content then.
BR
Micha

**Comment by MichaelSchaaf999** [comment]
Der Adapter müllt mir seit gestern das Log zu mit...
<html><head></head><body>
myuplink.0 | 2024-05-14 17:01:08.174 | error | Error: Bad Request: {  "error": "invalid_client",  "error_description": "check authorization server configuration",  "code": "invalid_client",  "description": "check authorization server configuration",  "timestamp": "2024-05-14T15:01:08.1634258+00:00" }
-- | -- | -- | --
myuplink.0 | 2024-05-14 17:01:08.174 | error | {  "message": "Request failed with status code 400",  "name": "AxiosError",  "stack": "AxiosError: Request failed with status code 400\n    at  settle  (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:1966:12)\n     at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:3065:11)\n     at IncomingMessage.emit (node:events:530:35)\n    at endReadableNT  (node:internal/streams/readable:1696:12)\n    at  process.processTicksAndRejections  (node:internal/process/task_queues:82:21)\n    at Axios.request  (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:3876:41)\n     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)\n    at async  AuthRepository.postTokenRequestAsync  (/opt/iobroker/node_modules/iobroker.myuplink/build/authRepository.js:128:24)\n     at async AuthRepository.getClientCredentialsGrantTokenAsync  (/opt/iobroker/node_modules/iobroker.myuplink/build/authRepository.js:100:22)\n     at async AuthRepository.getAccessTokenAsync  (/opt/iobroker/node_modules/iobroker.myuplink/build/authRepository.js:69:23)\n     at async Myuplink.getDataAsync  (/opt/iobroker/node_modules/iobroker.myuplink/build/main.js:157:29)\n     at async  /opt/iobroker/node_modules/iobroker.myuplink/build/main.js:184:9",  "config": {   "transitional": {    "silentJSONParsing": true,    "forcedJSONParsing": true,    "clarifyTimeoutError": false   },   "adapter": [    "xhr",    "http"   ],   "transformRequest": [    null   ],   "transformResponse": [    null   ],   "timeout": 45000,   "xsrfCookieName": "XSRF-TOKEN",   "xsrfHeaderName": "X-XSRF-TOKEN",   "maxContentLength": -1,   "maxBodyLength": -1,   "env": {},   "headers": {    "Accept": "application/json, text/plain, */*",    "Content-Type": "application/x-www-form-urlencoded",    "user-agent": "iobroker.myuplink",    "Content-Length": "152",    "Accept-Encoding": "gzip, compress, deflate, br"   },   "baseURL": "https://api.myuplink.com",   "method": "post",   "url": "/oauth/token",   "data":  "grant_type=client_credentials&client_id=4fd0bf1d-6704-4625-b624-2eefe549b747&client_secret=B43896C285EE9DF6CD32C1B17EBC13E0&scope=READSYSTEM+WRITESYSTEM"  },  "code": "ERR_BAD_REQUEST",  "status": 400 }
myuplink.0 | 2024-05-14 17:01:08.174 | error | error from /oauth/token

</body></html>

Mache ich hier was falsch? Diesen umfangreichen Meldungen kann ich irgendwie nicht entnehmen, wie man da vorgehen soll.

**Comment by MichaelSchaaf999** [comment]
p.s.: Ah, selber zufällig erkannt - der Adapter verbindet sich nicht mehr...
<img width="598" alt="image" src="https://github.com/sebilm/ioBroker.myuplink/assets/53481090/44ab153f-0b64-4326-8092-bb78a144a318">


Hat sich da irgendetwas geändert?
Identifier und Secret sind ja einegetragen und haben sich ja wohl auch nicht geändert.
<img width="1363" alt="image" src="https://github.com/sebilm/ioBroker.myuplink/assets/53481090/03ce078e-9962-40d5-80e0-38bc6b3874cc">


Was muss ich da bitte tun?
LG 
Micha

**Comment by Meintre** [comment]
Hallo,
ich möchte mich hier mal reinhängen. 
Ich habe eine Nibe f750. Mir fehlt leider der Datenpunkt 47260 (Lüftergeschwindigkeit). Kann man diesen Datenpunkt hinzufügen?
LG
Meintre

**Comment by sebilm** [comment]
Leider kann man keine Datenpunkte hinzufügen beim Lesen - ich habe es versucht. Wenn Datenpunkte nicht mit gesendet werden, kann man diese nicht explizit lesen, aber schreiben geht über den "setData"-Eintrag im Objekt-Baum vom myuplink-Adpater.

**Comment by Meintre** [comment]
Vielen Dank für die Antwort,habe es so gemacht und die Rückmeldung kommt über %.Sehr guter Adapter! Vielen DankGruß MeinhardVon meinem iPad gesendetAm 22.02.2025 um 10:45 schrieb Sebastian Haesselbarth ***@***.***>:﻿
  Leider kann man keine Datenpunkte hinzufügen beim Lesen - ich habe es versucht. Wenn Datenpunkte nicht mit gesendet werden, kann man diese nicht explizit lesen, aber schreiben geht über den "setData"-Eintrag im Objekt-Baum vom myuplink-Adpater.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



sebilm left a comment (sebilm/ioBroker.myuplink#28)
Leider kann man keine Datenpunkte hinzufügen beim Lesen - ich habe es versucht. Wenn Datenpunkte nicht mit gesendet werden, kann man diese nicht explizit lesen, aber schreiben geht über den "setData"-Eintrag im Objekt-Baum vom myuplink-Adpater.
