### ISSUE TITLE
Please integrate the new 2-Factor Authentification on myuplink

### ISSUE THREAD

**Issue by soulfire89** [sebilm/ioBroker.myuplink#86]
MyUplink set up a 2-Factor Authentification which sends a link with a random key to the registered Mail adress.

![image](https://github.com/user-attachments/assets/7d003a0b-3a5a-42a3-b4c0-f410851dcee8)

Please try to fix it, because the adapter usage is not possible.

The Adapter can't login anymore since this change and causes log entries like these every 30 seconds:

`"Error: Gateway Time-out: "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr> <center>Microsoft-Azure-Application-Gateway/v2</center>\r\n</body>\r\n</html>\r\n""`

`"{ "message": "Request failed with status code 504", "name": "AxiosError", "stack": "AxiosError: Request failed with status code 504\n at settle (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:2019:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:3135:11)\n at IncomingMessage.emit (node:events:530:35)\n at endReadableNT (node:internal/streams/readable:1698:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n at Axios.request (/opt/iobroker/node_modules/iobroker.myuplink/node_modules/axios/dist/node/axios.cjs:4287:41)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async MyUplinkRepository.getFromMyUplinkAsync (/opt/iobroker/node_modules/iobroker.myuplink/build/myUplinkRepository.js:67:24)\n at async MyUplinkLogic.setSystemDeviceAsync (/opt/iobroker/node_modules/iobroker.myuplink/build/myUplinkLogic.js:282:30)\n at async MyUplinkLogic.setSystemWithDevicesAsync (/opt/iobroker/node_modules/iobroker.myuplink/build/myUplinkLogic.js:231:11)\n at async MyUplinkLogic.GetDataAsync (/opt/iobroker/node_modules/iobroker.myuplink/build/myUplinkLogic.js:149:11)\n at async Myuplink.getDataAsync (/opt/iobroker/node_modules/iobroker.myuplink/build/main.js:292:21)\n at async /opt/iobroker/node_modules/iobroker.myuplink/build/main.js:309:9", "config": { "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false }, "adapter": [ "xhr", "http", "fetch" ], "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 45000, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "env": {}, "headers": { "Accept": "application/json, text/plain, */*", "user-agent": "iobroker.myuplink", "Authorization": "Bearer XXX", "Accept-Language": "de", "Accept-Encoding": "gzip, compress, deflate, br" }, "baseURL": "https://api.myuplink.com", "method": "get", "url": "/v3/devices/emmy-r-XXX/points" }, "code": "ERR_BAD_RESPONSE", "status": 504 }"`

*Token and device XXX

**Comment by sebilm** [comment]
I do not believe that the error (504, gateway timeout) has anything to do with 2-factor authentication. I have the same error and I don't have 2-factor authentication on. Let me have a look.

**Comment by sebilm** [comment]
It is as I suspected: You don't need 2FA for the API. The errors above have also disappeared in the meantime - it was a server problem.
